apiVersion: v1
kind: Pod
metadata:
  name: liveapp
  labels:
    name: liveapp
spec:
  containers:
  - name: liveapp
    image: cfsaju/liveapp
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
    
---
apiVersion: v1
kind: Service
metadata:
  name: liveapp-service
  labels:
    name: liveapp
spec:
  selector:
    app: liveapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
  type: NodePort




       
        
